#!/usr/bin/env python

print(type(True))
print(type(1))
print(type(1.0))
print(type(1j))
print(type((1,2,3,4)))
print(type([1,2,3,4]))
print(type({'a':'b'}))
print(type({'a', 'b', 'c'}))
print(type("Hello World"))
print(type('a'))
print(0xf3)
print(0o33)
print(0b011)